name: Deploy to VPS

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "deploy"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "repo"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            git pull
            echo $RSYNC_STDOUT

      - name: connect and pull
        run: | 
          echo ${{ secrets.REMOTE_USER }}
          echo ${{ secrets.REMOTE_HOST }}
          ssh -t -t ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
          
      - name: cleanup
        run: rm -rf ~/.ssh
