name: Deploy to VPS

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "${{ deploy }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/repo/codelab-loader/plasmedis-web

            # Atualizar o repositório
            git pull origin development

            # Construir e rodar os contêineres Docker
            cd /root/repo/codelab-loader/
            docker-compose down plasmedis-web
            docker-compose up -d --build plasmedis-web
          EOF
