name: Deploy to VPS

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "deploy"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh-keygen -R $SSH_HOST
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          SSH_HOST: ${{ secrets.VPS_HOST }}

      - name: connect and pull
        run: | 
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} /bin/bash
          cd repo/codelab-loader/plasmedis-web && git pull && exit
      - name: cleanup
        run: rm -rf ~/.ssh
