name: Deploy to VPS

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "deploy"

      - name: Checkout code
        uses: actions/checkout@v4

      # Make sure the @v0.9.0 matches the current version of the action
      -   name: Setup key
          uses: ./
          with:
              ssh-private-key: |
                  ${{ secrets.MPDUDE_TEST_1_DEPLOY_KEY }}
                  ${{ secrets.MPDUDE_TEST_2_DEPLOY_KEY }}

      - name: connect and pull
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /repo/codelab-loader/plasmedis-web && git pull && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
